K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Models/PieReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HDMS.Models
{
    public class PieReport
    {
        public string Labels { get; set; }
        public string Numbers { get; set; }
        public string Cityname { get; set; }
    }
}

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Controllers/PieReportController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HDMS.Models;

namespace HDMS.Controllers
{
    public class PieReportController : Controller
    {
        private HDMSEntities db = new HDMSEntities();
        //
        // GET: /PieReport/

        public ActionResult Index()
        {
            ViewBag.Cities = new SelectList(db.CityProvinces.ToArray(), "CityProvinceId", "Name");
            return View();
        }

        //
        // POST: /PieReport/DistrictPie

        [HttpPost]
        public ActionResult DistrictPie(int cityProvince)
        {
            //var ordersInCity = db.Orders.Where(o => o.District.CityProvinceId == 1);
            int id = 0;
            string name = "null city";

            if(cityProvince != 0)
            {
                id = cityProvince;
                name = db.CityProvinces.Single(n => n.CityProvinceId == id).Name;
            }

            PieReport allData = new PieReport();

            if(id > 0)
            {
                var districts = db.Districts;
                string countResult = "";
                string districtsName = "";
                foreach (var district in districts)
                {
                    if (district.CityProvinceId == id)
                    {
                        if (district.Orders.Count() > 0)
                        {
                            districtsName = (districtsName + "\"" + district.Name + "\"" + ",");
                            countResult = (countResult + district.Orders.Count() + ",");
                        }
                    }


                }
                if (districtsName.Length > 0)
                {
                    districtsName = "[" + districtsName.Substring(0, districtsName.Length - 1) + "]";
                    countResult = "[" + countResult.Substring(0, countResult.Length - 1) + "]";
                }
                allData.Labels = districtsName;
                allData.Numbers = countResult;
            }
            else
            {
                allData.Labels = "[]";
                allData.Numbers = "[]";
            }

            allData.Cityname = name;

            

            

            return View(allData);
        }

    }
}

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Views/PieReport/DistrictPie.cshtml
@model HDMS.Models.PieReport
@{
    ViewBag.Title = "DistrictPie";
}
<script src="/js/RGraph/RGraph.common.core.js"></script>
<script src="/js/RGraph/RGraph.common.tooltips.js"></script>
<script src="/js/RGraph/RGraph.common.dynamic.js"></script>
<script src="/js/RGraph/RGraph.common.effects.js"></script>
<script src="/js/RGraph/RGraph.pie.js"></script>
<div class="page-header">
    <h2>Orders Per District of @Model.Cityname</h2>
</div>

<div>
    <canvas id="cvs" width="600" height="400">[No canvas support]</canvas>
    <script>
        $(document).ready(function () {

            var data = @Model.Numbers;
            var labels = @Html.Raw(Model.Labels);
            
            var total = 0;
            for (var i = 0; i < data.length; ++i) {
                total = total + data[i];
            }
            var pie = new RGraph.Pie('cvs', data);
            pie.Set('chart.linewidth', 3);
            pie.Set('chart.exploded', [15, ]);
            pie.Set('chart.shadow', true);
            pie.Set('chart.shadow.offsetx', 0);
            pie.Set('chart.shadow.offsety', 0);
            pie.Set('chart.shadow.blur', 20);
            //pie.Set('chart.labels.sticks', [true]);
            //pie.Set('chart.labels.sticks.length', 3);
            RGraph.Effects.Pie.RoundRobin(pie);
            pie.Set('chart.tooltips', labels);
            pie.Set('chart.tooltips.event', 'onmousemove');
            pie.Set('chart.labels', labels);
            for (var u = 0; u < data.length; ++u) {
                pie.Get('chart.labels')[u] = pie.Get('chart.labels')[u] + ': ' + parseFloat((data[u] / total) * 100).toFixed(2) + '%';
            }
            pie.Draw();
        });
    </script>
</div>

<table border="2" cellspacing="2" cellpadding="5">
            <thead>
            <tr><th colspan="3"><center><h3>Orders Per District of @Model.Cityname</h3></center></th></tr>
            <tr>
            <th>District</th>
            <th>Orders</th>
            <th>Percent</th>
            </tr>
            </thead>
            <script>
                var data = @Model.Numbers;
                var labels = @Html.Raw(Model.Labels);
                var total = 0;
                for (var i = 0; i < data.length; ++i) {
                    total = total + data[i];
                }
                var str = "";
                for (var o = 0; o < data.length; o++) {
                    str = str + '<tr>';
                    str = str + '<td>' + labels[o] + '</td>';
                    str = str + '<td>' + data[o] + '</td>';
                    str = str + '<td>' + parseFloat((data[o] / total) * 100).toFixed(2) + '</td>';
                    str = str + '</tr>';
                }
                document.write(str);
            </script>
            
            </table>

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Views/PieReport/Index.cshtml
@model HDMS.Models.PieReport
@{
    ViewBag.Title = "Index";
}
<div class="page-header">
    <h2>Orders Per District Report</h2>
</div>
<fieldset>
    @using (Html.BeginForm("DistrictPie", "PieReport", FormMethod.Post, new { id = "create-form" }))
    {
        <div class="editor-label">
            City/Province
        </div>
        <div class="editor-field">
            @Html.DropDownList("CityProvince", ViewBag.Cities as SelectList, "-- Choose a City/Province --", new { id = "ddlCityProvince", Class = "chzn-select" })
        </div>
    }
</fieldset>
<input id="btnCreate" type="submit" class="btn btn-primary" value="Create Report" />
<script>
    $('#btnCreate').click(function () {
        var id = $('#ddlCityProvince option:selected').val();
        if (id > 0) {
            $('#create-form').submit();
        } else {
        alert("You must choose a City Province to create report!")
        }
    }); 
</script>