K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Models/Request.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int RequestId { get; set; }
        public System.Guid CreatedByUserId { get; set; }
        public int CustomerId { get; set; }
        public int CollectionAddressId { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<int> CollectionPlanId { get; set; }
        public int RequestStatus { get; set; }
        public string Note { get; set; }
    
        public virtual CollectionPlan CollectionPlan { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Models/ViewModels/RequestViewModel.cs
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using HDMS.Models;
using HDMS.Models.Utilities;
using HDMS.Models.ViewModels;

public partial class RequestViewModel
{
    public int RequestId { get; set; }
    public string Customer { get; set; }
    public string CollectionAddress { get; set; }
    public string RequestedDate { get; set; }
    public string Status { get; set; }
    public string Note { get; set; }
    public Nullable<decimal> Latitude { get; set; }
    public Nullable<decimal> Longitude { get; set; }
    public string AddressFromWard { get; set; }

    public RequestViewModel(Request request)
    {
        RequestId = request.RequestId;
        Customer = request.Customer.DisplayName;
        CollectionAddress = request.CustomerAddress.FullAddress;
        RequestedDate = string.Format("{0:dd/MM/yyyy tt}", request.RequestedDate);
        Status = Regex.Replace(request.Status.ToString(), "(\\B[A-Z])", " $1");
        Note = request.Note;
        Latitude = request.CustomerAddress.Latitude;
        Longitude = request.CustomerAddress.Longitude;
        AddressFromWard = AddressHelper.GetAddressFromWard(request.CustomerAddress);
    }
}

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.OleDb;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using HDMS.Models;
using HDMS.Models.Statuses;

namespace HDMS.Controllers
{
    public class RequestController : StaffDefaultController
    {
        private HDMSEntities context = new HDMSEntities();

        //
        // GET: /Requests/

        public ViewResult Index()
        {
            var requests = new List<Request>();
            var statuses = new List<int>();
            statuses.Add((int)RequestStatus.New);
            statuses.Add((int)RequestStatus.Approved);
            statuses.Add((int)RequestStatus.PlannedForCollecting);
            statuses.Add((int)RequestStatus.Collected);
            try
            {
                if (!string.IsNullOrEmpty(Request["status"]))
                {
                    var statusStrs = Request["status"].Split(',');
                    if (statusStrs.Count() > 0)
                    {
                        statuses = new List<int>();
                        foreach (var statusStr in statusStrs)
                        {
                            switch (statusStr.ToLower())
                            {
                                case "draft": statuses.Add((int)RequestStatus.Draft);
                                    break;
                                case "new": statuses.Add((int)RequestStatus.New);
                                    break;
                                case "approved": statuses.Add((int)RequestStatus.Approved);
                                    break;
                                case "planned": statuses.Add((int)RequestStatus.PlannedForCollecting);
                                    break;
                                case "collected": statuses.Add((int)RequestStatus.Collected);
                                    break;
                                case "finished": statuses.Add((int)RequestStatus.Finished);
                                    break;
                                case "canceled": statuses.Add((int)RequestStatus.Canceled);
                                    break;
                            }
                        }
                    }
                }
            }
            catch (Exception e)
            {
            }

            requests = context.Requests.Where(r => statuses.Contains(r.RequestStatus)).ToList();

            if (!string.IsNullOrWhiteSpace(Request["startDate"]))
            {
                var startDate = DateTime.ParseExact(Request["startDate"], "ddMMyyyy", null);
                requests = requests.Where(r => r.RequestedDate >= startDate).ToList();
                ViewBag.StartDate = string.Format("{0:dd/MM/yyyy}", startDate);
            }
            if (!string.IsNullOrWhiteSpace(Request["endDate"]))
            {
                var endDate = DateTime.ParseExact(Request["endDate"], "ddMMyyyy", null).AddDays(1);
                requests = requests.Where(r => r.RequestedDate <= endDate).ToList();
                ViewBag.EndDate = string.Format("{0:dd/MM/yyyy}", DateTime.ParseExact(Request["endDate"], "ddMMyyyy", null));
            }

            ViewBag.SelectedStatuses = statuses;
            return View(requests);
        }

        //
        // GET: /Requests/Details/5

        public ViewResult Details(int id)
        {
            Request request = context.Requests.Find(id);
            if (request != null)
            {
                return View(request);
            }
            throw new HttpException(404, "Not found!");
        }

        //
        // POST: /Requests/Create

        [HttpPost]
        public ActionResult Create()
        {
            ViewBag.PossibleCustomers = context.Customers.Where(c => c.IsActive);
            ViewBag.PossibleCollectionAddresses = new SelectList(new List<CustomerAddress>());
            return View();
        }

        //
        // POST: /Requests/Create

        [HttpPost]
        public ActionResult ConfirmCreate(int CustomerId, int CollectionAddressId, string Note, HttpPostedFileBase excelFile)
        {
            try
            {
                var request = new Request
                                  {
                                      CustomerId = CustomerId,
                                      CollectionAddressId = CollectionAddressId,
                                      Note = Note
                                  };
                if (request.Create(context))
                {
                    if (excelFile != null)
                    {
                        string savedFileName = "~/Excel/" + excelFile.FileName;
                        excelFile.SaveAs(Server.MapPath(savedFileName));

                        var connectionString = string.Format("Provider=Microsoft.ACE.OLEDB.12.0;Data Source={0};Extended Properties=Excel 12.0;", Server.MapPath(savedFileName));
                        OleDbConnection objConn = new OleDbConnection(connectionString);
                        objConn.Open();
                        var dt = objConn.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);

                        String[] excelSheets = new String[dt.Rows.Count];
                        int x = 0;

                        foreach (DataRow row in dt.Rows)
                        {
                            excelSheets[x] = row["TABLE_NAME"].ToString();
                            x++;
                        }

                        for (int j = 0; j < excelSheets.Length; j++)
                        {
                            if (excelSheets[j].Contains("Order"))
                            {
                                var adapter = new OleDbDataAdapter("SELECT * FROM " + "[" + excelSheets[j] + "]", connectionString);
                                var ds = new DataSet();
                                adapter.Fill(ds, "results");
                                DataTable data = new DataTable();
                                data = ds.Tables["results"];

                                var orders = new List<Order>();
                                var items = new List<Item>();

                                Order order = new Order();

                                for (int i = 0; i < data.Rows.Count; i++)
                                {
                                    var receiverName = data.Rows[i].Field<string>("Receiver Name");
                                    var receiverPhone = data.Rows[i].Field<string>("Receiver Phone");
                                    var receiverAddress = data.Rows[i].Field<string>("Receiver Address");
                                    var drOption = data.Rows[i].Field<string>("Delivery Option");
                                    var orPaymentType = data.Rows[i].Field<string>("Order Payment Type");
                                    var cityName = data.Rows[i].Field<string>("City");
                                    var districtName = data.Rows[i].Field<string>("District");
                                    var wardName = data.Rows[i].Field<string>("Ward");
                                    var amount = data.Rows[i].Field<string>("Amount");

                                    if (i == 0)
                                    {
                                        if (string.IsNullOrEmpty(receiverName) == false && string.IsNullOrEmpty(receiverPhone) == false
                                            && string.IsNullOrEmpty(receiverAddress) == false && string.IsNullOrEmpty(amount) == false 
                                            && string.IsNullOrEmpty(drOption) == false && string.IsNullOrEmpty(orPaymentType) == false
                                            && string.IsNullOrEmpty(districtName) == false && string.IsNullOrEmpty(cityName) == false
                                            && string.IsNullOrEmpty(wardName) == false)
                                        {
                                            var deliveryOption = context.DeliveryOptions.Single(dr => dr.Name == drOption);
                                            var orderPaymentType = context.OrderPaymentTypes.Single(op => op.Name == orPaymentType);
                                            var district = context.Districts.Single(di => di.Name == districtName);
                                            var ward = context.Wards.Single(w => w.Name == wardName && w.DistrictId == district.DistrictId);

                                            order.RequestId = request.RequestId;
                                            order.DeliveryOptionId = deliveryOption.DeliveryOptionId;
                                            order.OrderPaymentTypeId = orderPaymentType.OrderPaymentTypeId;
                                            order.ReceiverName = receiverName;
                                            order.ReceiverPhone = receiverPhone;
                                            order.ReceiverAddress = receiverAddress;
                                            order.ReceiverAddressDistrictId = district.DistrictId;
                                            order.ReceiverAddressWardId = ward.WardId;
                                            order.AmountToBeCollectedFromReceiver = int.Parse(amount);
                                            order.Note = data.Rows[i].Field<string>("Note");

                                            orders.Add(order);
                                            context.Orders.Add(order);
                                        }else
                                        {
                                            return View("CreateUnsuccessful");

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Views/Request/Create.cshtml
@model HDMS.Models.Request
@{
    Layout = null;
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        ×</button>
    <h3 id="myModalLabel">
        Create new Request</h3>
</div>
<div class="modal-body" style="height: 400px;">
    @using (Html.BeginForm("ConfirmCreate", "Request", FormMethod.Post, new { id = "create-form", Enctype = "multipart/form-data", Class = "form-horizontal" }))
    {
        @Html.ValidationSummary(true)            
        <div class="control-group">
            <label class="control-label">
                Customer <span style="color:Red">*</span>
            </label>
            <div class="controls">
                @Html.DropDownListFor(model => model.CustomerId, ((IEnumerable<HDMS.Models.Customer>)ViewBag.PossibleCustomers).Select(option => new SelectListItem
       {
           Text = Html.DisplayTextFor(_ => option.DisplayName).ToString(),
           Value = option.CustomerId.ToString(),
           Selected = (Model != null) && (option.CustomerId == Model.CustomerId)
       }), "-- Choose a Customer --", new { id = "ddlCustomer", Class = "chzn-select" })
                @Html.ValidationMessageFor(model => model.CustomerId)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">
                Collection Address <span style="color:Red">*</span>
            </label>
            <div class="controls">
                @*Html.EditorFor(model => model.CollectionAddressId)*@
                @Html.DropDownListFor(model => model.CollectionAddressId, ViewBag.PossibleCollectionAddresses as SelectList, "-- Choose a Collection Address --", new { id = "ddlCollectionAddress", Class = "chzn-select" })
                @Html.ValidationMessageFor(model => model.CollectionAddressId)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">
                Note
            </label>
            <div class="controls">
                @Html.TextAreaFor(model => model.Note)
                @Html.ValidationMessageFor(model => model.Note)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">
                Excel file
            </label>
            <div class="controls">
                <input type="file" id="excelFile" name="excelFile" />  
            </div>
        </div>
        
    }
</div>
<div class="modal-footer">
    <input id="btnCreate" type="submit" class="btn btn-primary" value="Create" />
    <button class="btn" data-dismiss="modal" aria-hidden="true">
        Cancel</button>
</div>
<script>
    //    $("#create-form").submit(function () {
    //        if ($(this).valid()) {
    //            $.ajax({
    //                type: 'POST',
    //                url: $(this).attr("action"),
    //                data: $(this).serialize(),
    //                success: function (result) {
    //                    if (result.success) {
    //                        window.location = '/Request/AddOrders/' + result.requestId;
    //                    }
    //                },
    //                async: false
    //            });
    //        }
    //        return false;
    //    });

    $('#btnCreate').click(function () {
        $('#create-form').submit();
    });

    $("#ddlCustomer").change(function () {
        var id = $('#ddlCustomer option:selected').val();
        if (id == '') id = -1;
        $.ajax({
            type: 'POST',
            url: '/CustomerAddresses/GetAddressesOfCustomer/' + id,
            success: function (data) {
                var items = '';
                $.each(data, function (i, address) {
                    items += "<option value='" + address.CustomerAddressId + "'>" + address.FullAddress + "</option>";
                });
                $('#ddlCollectionAddress').html(items);
                $('#ddlCollectionAddress').removeAttr('data-val-number');
                $("form").removeData("validator");
                $("form").removeData("unobtrusiveValidation");
                $.validator.unobtrusive.parse("form");
                $('#ddlCollectionAddress').trigger("liszt:updated");
            },
            async: false
        });
    });
    $(".chzn-select").chosen();
    $(".chzn-select-deselect").chosen({ allow_single_deselect: true });

    $(".datepicker").datepicker();
</script>
<script>
    $('#uploadExcelForm').submit(function () {
        if (document.getElementById('excelFile').value.match(/xls$/) || document.getElementById('excelFile').value.match(/xlsx$/)) {
            return true;
        } else {
            alert('Must be a excel file !!!!!');
            return false;
        }
    });
</script>

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Views/Request/CreateUnsuccessful.cshtml
@{
    ViewBag.Title = "CreateUnsuccessful";
}

<div class="page-header">
	<h2>CreateUnsuccessful</h2>
    <p>Format is not correct. Please check your Excel file again !!!</p>
</div>

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Views/Request/Delete.cshtml
@model HDMS.Models.Request

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Request</legend>

    <div class="display-label">CollectionAddressId</div>
    <div class="display-field">@Model.CollectionAddressId</div>

    <div class="display-label">RequestedDate</div>
    <div class="display-field">@String.Format("{0:dd/MM/yyyy hh:mm tt}", Model.RequestedDate)</div>

    <div class="display-label">RequestStatus</div>
    <div class="display-field">@Model.RequestStatus</div>

    <div class="display-label">Note</div>
    <div class="display-field">@Model.Note</div>

    <div class="display-label">Collection</div>
    <div class="display-field">@Html.DisplayTextFor(_ => Model.Collection).ToString()</div>

    <div class="display-label">CustomerPayment</div>
    <div class="display-field">@Html.DisplayTextFor(_ => Model.CustomerPayment).ToString()</div>

    <div class="display-label">Customer</div>
    <div class="display-field">@Html.DisplayTextFor(_ => Model.Customer).ToString()</div>

    <div class="display-label">CustomerAddress</div>
    <div class="display-field">@Html.DisplayTextFor(_ => Model.CustomerAddress).ToString()</div>

    <div class="display-label">Orders</div>
    <div class="display-field">@(Model.Orders == null ? "None" : Model.Orders.Count.ToString())</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}



K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Views/Request/Edit.cshtml
@model HDMS.Models.Request

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Request</legend>

        @Html.HiddenFor(model => model.RequestId)
		@Html.Partial("_CreateOrEdit", Model)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Views/Request/RequestTable.cshtml
@model IEnumerable<HDMS.Models.Request>
@using System.Text.RegularExpressions;  
@{ 
    Layout = null;
}
<table class="table table-striped table-bordered" id="main-table">
        <thead>
            <tr>
                <th>
                    Request No.
                </th>
                <th>
                    Requested Date
                </th>
                <th>
                </th>
                <th>
                    Customer
                </th>
                <th>
                    Orders
                </th>
                <th>
                    Collection Address
                </th>
                <th>
                    Status
                </th>
                <th>
                    Note
                </th>
                <th class="tbl-action-col">
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        #@item.RequestId
                    </td>
                    <td>
                        @if (item.RequestedDate != null)
                        {
                            @String.Format("{0:dd/MM/yyyy hh:mm tt}", item.RequestedDate)
                        }
                    </td>
                    <td>
                        @if (item.RequestedDate != null)
                        {
                            @String.Format("{0:yyyyMMddHHmm}", item.RequestedDate)
                        }
                        else
                        {
                            <text>000</text>
                        }
                    </td>
                    <td>
                        @Html.DisplayTextFor(_ => item.Customer.DisplayName).ToString()
                    </td>
                    <td>
                        @item.ValidOrders.Count
                    </td>
                    <td>@item.CollectionAddress
                    </td>
                    <td style="min-width:65px;">
                        @Regex.Replace(item.Status.ToString(), "(\\B[A-Z])", " $1")
                        @if (item.Status == HDMS.Models.Statuses.RequestStatus.Draft)
                        {
                            <a class="update btn action" href="/Request/AddOrders/@item.RequestId">
                                <img src="/img/icons/pencil.png" alt="Edit" title="Edit" /></a>   
                        }
                        
                        @if (item.Status == HDMS.Models.Statuses.RequestStatus.New)
                        {
                            <a class="update btn action" href="/Request/ApproveOrders/@item.RequestId">
                                <img src="/img/icons/arrow_right2.png" alt="Approve Orders" title="Approve Orders" /></a>   
                        }
                    </td>
                    <td>
                        @item.Note
                    </td>
                    <td class="action-column"@if (item.Status == HDMS.Models.Statuses.RequestStatus.Draft){<text>style="min-wid"</text>}>
                        <a class="btn action view" href="/Request/Details/@item.RequestId">
                            <img src="/img/icons/notepad.png" alt="View" title="View" width="15px"></a> 
                        @*<a class="btn action update" href="#" onclick="showUpdateStatusModal(@item.RequestId,@item.RequestStatus)">
                                <img src="/img/icons/arrow_bidirectional.png" alt="Update Status" title="Update Status" width="15px" /></a>*@ 
                        @if (item.Status != HDMS.Models.Statuses.RequestStatus.Finished)
                        {
                                if (item.Status != HDMS.Models.Statuses.RequestStatus.Canceled)
                                {
                                    <a class="btn action delete" href="#" onclick="cancelRequest(@item.RequestId);">
                                        <img src="/img/icons2/cross.png" alt="Cancel" title="Cancel Request" width="15px"/>
                                    </a> 
                                }
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Views/Request/_CreateOrEdit.cshtml
@model HDMS.Models.Request
@* This partial view defines form fields that will appear when creating and editing entities *@
<script src="/js/chosen.jquery.js" type="text/javascript"></script>
<div class="form-horizontal">
    <div class="control-group">
        <label class="control-label">
            Customer
        </label>
        <div class="controls">
            @Html.DropDownListFor(model => model.CustomerId, ((IEnumerable<HDMS.Models.Customer>)ViewBag.PossibleCustomers).Select(option => new SelectListItem
       {
           Text = Html.DisplayTextFor(_ => option.DisplayName).ToString(),
           Value = option.CustomerId.ToString(),
           Selected = (Model != null) && (option.CustomerId == Model.CustomerId)
       }), "-- Choose a Customer --", new { id = "ddlCustomer", Class = "chzn-select" })
            @Html.ValidationMessageFor(model => model.CustomerId)
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">
            Collection Address Id
        </label>
        <div class="controls">
            @*Html.EditorFor(model => model.CollectionAddressId)*@
            @Html.DropDownListFor(model => model.CollectionAddressId, ViewBag.PossibleCollectionAddresses as SelectList, "-- Choose a Collection Address --", new { id = "ddlCollectionAddress", Class = "chzn-select" })
            @Html.ValidationMessageFor(model => model.CollectionAddressId)
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">
            Note
        </label>
        <div class="controls">
            @Html.TextAreaFor(model => model.Note)
            @Html.ValidationMessageFor(model => model.Note)
        </div>
    </div>
</div>
<script>
    $("#ddlCustomer").change(function () {
        var id = $('#ddlCustomer option:selected').val();
        if (id == '') id = -1;
        $.ajax({
            type: 'POST',
            url: '/CustomerAddresses/GetAddressesOfCustomer/' + id,
            success: function (data) {
                var items = '';
                $.each(data, function (i, address) {
                    items += "<option value='" + address.CustomerAddressId + "'>" + address.FullAddress + "</option>";
                });
                $('#ddlCollectionAddress').html(items);
                $('#ddlCollectionAddress').removeAttr('data-val-number');
                $("form").removeData("validator");
                $("form").removeData("unobtrusiveValidation");
                $.validator.unobtrusive.parse("form");
                $('#ddlCollectionAddress').trigger("liszt:updated");
            },
            async: false
        });
    });
    $(".chzn-select").chosen();
    $(".chzn-select-deselect").chosen({ allow_single_deselect: true });
</script>