K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Models/Contact.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public int CustomerId { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HDMS.Models;

namespace HDMS.Controllers
{
    public class ContactsController : StaffDefaultController
    {
        private HDMSEntities context = new HDMSEntities();

        //
        // GET: /Contacts/

        //public ViewResult Index()
        //{
        //    return View(context.Contacts.Where(c => c.IsActive).ToList());
        //}

        //
        // GET: /Contacts/Details/5

        //public ViewResult Details(int id)
        //{
        //    Contact contact = context.Contacts.Find(id);
        //    return View(contact);
        //}

        //
        // POST: /Contacts/Create

        [HttpPost]
        public ActionResult Create()
        {
            ViewBag.PossibleCustomers = context.Customers.Where(c => c.IsActive);
            var possibleTitles = new List<string>();
            possibleTitles.Add("Mr.");
            possibleTitles.Add("Ms.");
            ViewBag.PossibleTitles = new SelectList(possibleTitles);
            return View();
        } 

        //
        // POST: /Contacts/ConfirmCreate

        [HttpPost]
        public ActionResult ConfirmCreate(Contact contact)
        {
            if (ModelState.IsValid)
            {
                contact.IsActive = true;
                context.Contacts.Add(contact);
                context.SaveChanges();
                return Json(new { success = true });
            }

            return Json(new { success = false });
        }
        
        //
        // POST: /Contacts/Edit/5
 
        [HttpPost]
        public ActionResult Edit(int id)
        {
            Contact contact = context.Contacts.Single(x => x.ContactId == id);
            ViewBag.PossibleCustomers = context.Customers.Where(c => c.IsActive);
            var possibleTitles = new List<string>();
            possibleTitles.Add("Mr.");
            possibleTitles.Add("Ms.");
            ViewBag.PossibleTitles = new SelectList(possibleTitles,contact.Title);
            return View(contact);
        }

        //
        // POST: /Contacts/ConfirmEdit/5

        [HttpPost]
        public ActionResult ConfirmEdit(Contact contact)
        {
            if (ModelState.IsValid)
            {
                context.Entry(contact).State = EntityState.Modified;
                context.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }

        //
        // GET: /Contacts/Delete/5
 
        public ActionResult Delete(int id)
        {
            Contact contact = context.Contacts.Find(id);
            return View(contact);
        }

        //
        // POST: /Contacts/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Contact contact = context.Contacts.Find(id);
            context.Contacts.Remove(contact);
            context.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                context.Dispose();
            }
            base.Dispose(disposing);
        }

        //
        // POST: /CustomerAddress/ToggleActivate/5

        //[HttpPost]
        //public ActionResult ToggleActivate(int id)
        //{

        //    Contact contact = context.Contacts.Find(id);
        //    contact.IsActive = !contact.IsActive;
        //    context.SaveChanges();
        //    return Json(new { isActive = contact.IsActive });
        //}

        //[HttpPost]
        //public ActionResult Remove(int id)
        //{
        //    try
        //    {
        //        var contact = context.Contacts.Find(id);
        //        contact.IsActive = false;
        //        context.SaveChanges();
        //        return Json(new { success = true });
        //    }
        //    catch (Exception)
        //    {
        //        return Json(new { success = false });
        //    }
        //}
    }
}

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Views/Contacts/Delete.cshtml
@model HDMS.Models.Contact

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Contact</legend>

    <div class="display-label">Title</div>
    <div class="display-field">@Model.Title</div>

    <div class="display-label">Name</div>
    <div class="display-field">@Model.Name</div>

    <div class="display-label">Position</div>
    <div class="display-field">@Model.Position</div>

    <div class="display-label">EmailAddress</div>
    <div class="display-field">@Model.EmailAddress</div>

    <div class="display-label">PhoneNumber</div>
    <div class="display-field">@Model.PhoneNumber</div>

    <div class="display-label">IsActive</div>
    <div class="display-field">@Model.IsActive</div>

    <div class="display-label">Customer</div>
    <div class="display-field">@Html.DisplayTextFor(_ => Model.Customer).ToString()</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}



K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Views/Contacts/Details.cshtml
@model HDMS.Models.Contact

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Contact</legend>

    <div class="display-label">Title</div>
    <div class="display-field">@Model.Title</div>

    <div class="display-label">Name</div>
    <div class="display-field">@Model.Name</div>

    <div class="display-label">Position</div>
    <div class="display-field">@Model.Position</div>

    <div class="display-label">EmailAddress</div>
    <div class="display-field">@Model.EmailAddress</div>

    <div class="display-label">PhoneNumber</div>
    <div class="display-field">@Model.PhoneNumber</div>

    <div class="display-label">IsActive</div>
    <div class="display-field">@Model.IsActive</div>

    <div class="display-label">Customer</div>
    <div class="display-field">@Html.DisplayTextFor(_ => Model.Customer).ToString()</div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ContactId }) |
    @Html.ActionLink("Back to List", "Index")
</p>



K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Views/Contacts/Edit.cshtml
@model HDMS.Models.Contact
@{
    Layout = null;
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        &times;</button>
    <h3>
        Edit Contact</h3>
</div>
<div class="modal-body">
    <fieldset>
        <div>
            @using (Html.BeginForm("ConfirmEdit", "Contacts", FormMethod.Post, new { id = "contact-edit-form" }))
            {
                @Html.ValidationSummary(true)
        
                @Html.HiddenFor(model => model.ContactId)
                @Html.HiddenFor(model => model.IsActive)
                @Html.Partial("_CreateOrEdit", Model)
      
            }
        </div>
    </fieldset>
</div>
<div class="modal-footer">
    <input type="submit" class="btn btn-primary" value="Save" id="btnSave" />
    <button class="btn" data-dismiss="modal" aria-hidden="true">
        Cancel</button>
</div>
<script type="text/javascript">
    $("#contact-edit-form").submit(function () {
        var success = false;
        if ($(this).valid()) {
            $.ajax({
                type: 'POST',
                url: $(this).attr("action"),
                data: $(this).serialize(),
                success: function (result) {
                    success = result.success;
                    if (success) {
                        $('#editModal').modal('hide');
                        refreshContactTable();
                    }
                },
                async: false
            });
        }
        return false;
    });
    
    $('#btnSave').click(function () {
        $('#contact-edit-form').submit();
    });
</script>

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Views/Contacts/Index.cshtml
@model IEnumerable<HDMS.Models.Contact>
@{
    ViewBag.Title = "Contacts";
    ViewBag.Heading = "Contacts";
@if (false)
{ 
    <script src="/js/jquery-1.8.2-vsdoc.js" type="text/javascript"></script>
}
<link rel="stylesheet" type="text/css" href="/css/DT_bootstrap.css" />
<link href="/css/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" charset="utf-8" language="javascript" src="/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf-8" language="javascript" src="/js/DT_bootstrap.js"></script>
<script src="/js/dataTables.bootstrap.js" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="/js/crud.js" type="text/javascript"></script>

<table class="table table-striped table-bordered" id="main-table">
    <thead>
        <tr>
            @*<th class="hide">
                ContactId
            </th>*@
            <th>
                Title
            </th>
            <th>
                Full Name
            </th>
            <th>
                Position
            </th>
            <th>
                Email Address
            </th>
            <th>
                Phone Number
            </th>
            <th class="tbl-status-col">
                Status
            </th>
            <th class="tbl-status-col">
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td class="hide">
                    @item.ContactId
                </td>*@
                <td>
                    @item.Title
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    @item.Position
                </td>
                <td>
                    @item.EmailAddress
                </td>
                <td>
                    @item.PhoneNumber
                </td>
                <td class="">
                    <a class="toggleActivate" href="#">
                        @if (item.IsActive)
                        {
                            <img src="/img/icons2/checkmark2.png" width="18px" height="18px" alt="Active - Click to Deactivate"
                                title="Active - Click to Deactivate" />
                        }
                        else
                        {
                            <img src="/img/icons2/delete.png" width="18px" height="18px" alt="Inactive - Click to Activate"
                                title="Deactive - Click to Activate" />
                        }
                    </a>
                </td>
                <td class="">
                    <a class="btn action edit" href="javascript:void(0)" onclick="edit(@item.ContactId)">
                        <img src="/img/icons/pencil.png" alt="Edit" title="Edit" /></a>
                </td>
            </tr>
        }
    </tbody>
</table>
<!-- Begin "Create" Modal -->
<div class="modal hide fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
    aria-hidden="true">
</div>
<!-- End "Create" Modal -->
<!-- Begin "Edit" Modal -->
<div class="modal hide fade" id="editModal">
</div>
<!-- End "Edit" Modal -->

K4C_Supplied/Source/trunk/Code/HDMS/HDMS/Views/Contacts/_CreateOrEdit.cshtml
@model HDMS.Models.Contact
@* This partial view defines form fields that will appear when creating and editing entities *@
<script src="/js/chosen.jquery.js" type="text/javascript"></script>
<script src="/js/bootstrap-typeahead.js" type="text/javascript"></script>
<div class="form-horizontal">
    <div class="control-group">
        <label class="control-label">
            Title <span style="color:Red">*</span>
        </label>
        <div class="controls">
            @Html.DropDownListFor(model => model.Title, ViewBag.PossibleTitles as SelectList, new { id = "title", Autocomplete = "off" })
            @Html.ValidationMessageFor(model => model.Title)
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">
            Full Name <span style="color:Red">*</span>
        </label>
        <div class="controls">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">
            Position
        </label>
        <div class="controls">
            @Html.TextBoxFor(model => model.Position, new { id = "position", Autocomplete = "off" })
            @Html.ValidationMessageFor(model => model.Position)
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">
            Email Address <span style="color:Red">*</span>
        </label>
        <div class="controls">
            @Html.EditorFor(model => model.EmailAddress)
            @Html.ValidationMessageFor(model => model.EmailAddress)
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">
            Phone Number <span style="color:Red">*</span>
        </label>
        <div class="controls">
            @Html.EditorFor(model => model.PhoneNumber)
            @Html.ValidationMessageFor(model => model.PhoneNumber)
        </div>
    </div>
</div>
@*<div class="editor-label">
    Customer
</div>
<div class="editor-field">
    @Html.DropDownListFor(model => model.CustomerId, ((IEnumerable<HDMS.Models.Customer>)ViewBag.PossibleCustomers).Select(option => new SelectListItem
{
    Text = (option == null ? "None" : option.CompanyName),
    Value = option.CustomerId.ToString(),
    Selected = (Model != null) && (option.CustomerId == Model.CustomerId)
}), "-- Choose a Customer --", new { Class = "chzn-select" })
    @Html.ValidationMessageFor(model => model.CustomerId)
</div>*@ @*tạm thời gán CustomerId cứng*@
<input type="hidden" name="CustomerId" id="CustomerId" value="" />
<script type="text/javascript">
    $('#Title').typeahead({
        source: [
            { id: 1, name: 'Mr' },
            { id: 2, name: 'Mrs' },
            { id: 3, name: 'Ms' },
        ]
    });
</script>
<script type="text/javascript">
    $('#Position').typeahead({
        source: [
            { id: 1, name: 'Manager' },
            { id: 2, name: 'Sale Executive' },
            { id: 3, name: 'Deliverer' },
        ]
    });
</script>